In [9]:
import pandas as pd
import numpy as np

In [10]:
data = pd.read_csv("./DATA/insurance_data.csv")
data.head()

,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01

## Cleaning our data

In [11]:
missing_values_row = data.isnull().any(axis=1)
print("Rows with missing values:")
print(data[missing_values_row])

Rows with missing values:
    index  PatientID   age gender   bmi  bloodpressure diabetic  children  \
2       2          3   NaN   male  33.3             82      Yes         0
3       3          4   NaN   male  33.7             80       No         0
4       4          5   NaN   male  34.1            100       No         0
5       5          6   NaN   male  34.4             96      Yes         0
6       6          7   NaN   male  37.3             86      Yes         0
13     13         14  32.0   male  27.6            100       No         0
14     14         15  40.0   male  28.7             81      Yes         0
15     15         16  32.0   male  30.4             86      Yes         0

   smoker     region    claim
2      No  southeast  1135.94
3      No  northwest  1136.40
4      No  northwest  1137.01
5      No  northwest  1137.47
6      No  northwest  1141.45
13     No        NaN  1252.41
14     No        NaN  1253.94
15     No        NaN  1256.30

In [12]:
# check duplicates
duplicates = data[data.duplicated()]
print("Duplicate rows:")
print(duplicates)

Duplicate rows:
Empty DataFrame
Columns: [index, PatientID, age, gender, bmi, bloodpressure, diabetic, children, smoker, region, claim]
Index: []

In [13]:
# calculatye percentage of each columns
percentage = data.isnull().mean() * 100
print(percentage)

index            0.000000
PatientID        0.000000
age              0.373134
gender           0.000000
bmi              0.000000
bloodpressure    0.000000
diabetic         0.000000
children         0.000000
smoker           0.000000
region           0.223881
claim            0.000000
dtype: float64

In [14]:
data.dropna(axis=0, inplace=True)
data.head()

,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
7,7,8,19.0,male,41.1,100,No,0,No,northwest,1146.80
8,8,9,20.0,male,43.0,86,No,0,No,northwest,1149.40
9,9,10,30.0,male,53.1,97,No,0,No,northwest,1163.46

In [15]:
# saving the cleaned data
data.to_csv("./DATA/cleaned_insurance_data.csv", index=False)